#This YAML file is a sample Daemonset to change the node to use AES-256-GCM encryption algorithm while mounting the Azure file share. 
apiVersion: v1
kind: ConfigMap
metadata:
  name: actions
  namespace: kube-system
data:
  run.sh: |
    #!/bin/bash
    cifsConfPath="/etc/modprobe.d/cifs.conf"
    echo "$(date) before change ${cifsConfPath}:"
    cat ${cifsConfPath}
    # Check if 'require_gcm_256' is already present in the configuration file
    if ! grep -q "require_gcm_256" "${cifsConfPath}"; then
      # Load the CIFS module
      modprobe cifs
      # Set the parameter at runtime
      echo 1 > /sys/module/cifs/parameters/require_gcm_256
      # Persist the configuration
      echo "options cifs require_gcm_256=1" >> "${cifsConfPath}"
      echo "$(date) after changing ${cifsConfPath}:"
      cat "${cifsConfPath}"
    else
      echo "require_gcm_256 is already set in ${cifsConfPath}"
    fi
    sleep 43200
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test
  namespace: kube-system
  labels:
    name: test
spec:
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      labels:
        name: test
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: test
        command: ["/bin/sh"]
        args: ["/tmp/run.sh"]
        image: alpine:3.7
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: sys
          mountPath: /etc
        - name: actions
          mountPath: /tmp
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sys
        hostPath:
          path: /etc
      - name: actions
        configMap:
          name: actions
