apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bpftrace-ds
  namespace: kube-system
  labels:
    app: bpftrace-ds
spec:
  selector:
    matchLabels:
      app: bpftrace-ds
  template:
    metadata:
      labels:
        app: bpftrace-ds
    spec:
      containers:
      - command:
        - nsenter
        - --target
        - "1"
        - --mount
        - --uts
        - --ipc
        - --net
        - --pid
        - bash
        - -c
        - "bpftrace -e 'kprobe:cifs_statfs { time(\"%H:%M:%S \"); printf(\"%-6d %-16s\\n\", pid, comm); }' || echo 'no probe, sleeping...'; sleep 10000"
        image: docker.io/library/alpine
        imagePullPolicy: Always
        name: nsenter
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          privileged: true
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
      - effect: NoSchedule
        key: appType
        operator: Exists
