---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: download-v6-disk-rules
  name: download-v6-disk-rules
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: download-v6-disk-rules
      tier: node
  template:
    metadata:
      labels:
        component: download-v6-disk-rules
        tier: node
    spec:
      containers:
        - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - sh
            - -c
            - |
              set -e
              echo "downloading 80-azure-disk.rules file to /etc/udev/rules.d/80-azure-disk.rules ..."
              wget -O /etc/udev/rules.d/80-azure-disk.rules https://raw.githubusercontent.com/Azure/azure-vm-utils/refs/heads/main/udev/80-azure-disk.rules
              udevadm control --reload-rules && udevadm trigger
              echo "80-azure-disk.rules is taking effect now"
              sleep 900000000s
          image: alpine
          imagePullPolicy: IfNotPresent
          name: download-v6-disk-rules
          resources:
            requests:
              cpu: 10m
          securityContext:
            privileged: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: RollingUpdate
