---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: increase-volume-stats-agg-period
  name: increase-volume-stats-agg-period
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: increase-volume-stats-agg-period
      tier: node
  template:
    metadata:
      labels:
        component: increase-volume-stats-agg-period
        tier: node
    spec:
      containers:
        - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - sh
            - -c
            - |
              kubeletPath="/etc/default/kubelet"
              echo "`date` before change kubelet flags:"
              cat ${kubeletPath}
              sed -i 's/volume-stats-agg-period=5m/volume-stats-agg-period=10m/g' ${kubeletPath}
              cat ${kubeletPath}
              systemctl daemon-reload
              systemctl restart kubelet
              sleep 600000000s
          image: alpine
          imagePullPolicy: IfNotPresent
          name: increase-volume-stats-agg-period
          resources:
            requests:
              cpu: 10m
          securityContext:
            privileged: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: OnDelete
