---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: tune-kube-api-qps
  name: tune-kube-api-qps
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: tune-kube-api-qps
      tier: node
  template:
    metadata:
      labels:
        component: tune-kube-api-qps
        tier: node
    spec:
      containers:
        - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - sh
            - -c
            - |
              kubeletPath="/etc/default/kubelet"
              echo "`date` before change kubelet flags:"
              cat ${kubeletPath}
              if !(( grep kube-api-qps ${kubeletPath} ))
              then
                sed -i 's/KUBELET_FLAGS=/KUBELET_FLAGS=--kube-api-qps=50 --kube-api-burst=100 /g' ${kubeletPath}
                echo "`date` after changing kubelet flags:"
                cat ${kubeletPath}
                systemctl daemon-reload
                systemctl restart kubelet
              fi
              sleep 600000000s
          image: alpine
          imagePullPolicy: IfNotPresent
          name: tune-kube-api-qps
          resources:
            requests:
              cpu: 10m
          securityContext:
            privileged: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: OnDelete
