apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-controller-manager
spec:
  priorityClassName: system-node-critical
  hostNetwork: true
  containers:
    - name: kube-controller-manager
      image: k8s.gcr.io/kube-controller-manager:v1.18.0-alpha.2
      imagePullPolicy: IfNotPresent
      command: ["kube-controller-manager"]
      args: ["--allocate-node-cidrs=false", "--cloud-config=/etc/kubernetes/azure.json", "--cloud-provider=azure", "--cluster-cidr=10.240.0.0/12", "--cluster-name=andy-1180alpha2x", "--cluster-signing-cert-file=/etc/kubernetes/certs/ca.crt", "--cluster-signing-key-file=/etc/kubernetes/certs/ca.key", "--configure-cloud-routes=false", "--controllers=*,bootstrapsigner,tokencleaner", "--feature-gates=LocalStorageCapacityIsolation=true,ServiceNodeExclusion=true,CSIMigrationAzureDisk=true", "--kubeconfig=/var/lib/kubelet/kubeconfig", "--leader-elect=true", "--node-monitor-grace-period=40s", "--pod-eviction-timeout=5m0s", "--profiling=false", "--root-ca-file=/etc/kubernetes/certs/ca.crt", "--route-reconciliation-period=10s", "--service-account-private-key-file=/etc/kubernetes/certs/apiserver.key", "--terminated-pod-gc-threshold=5000", "--use-service-account-credentials=true", "--v=2"]
      volumeMounts:
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: etc-ssl
          mountPath: /etc/ssl
          readOnly: true
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: msi
          mountPath: /var/lib/waagent/ManagedIdentity-Settings
          readOnly: true
  volumes:
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: etc-ssl
      hostPath:
        path: /etc/ssl
    - name: var-lib-kubelet
      hostPath:
        path: /var/lib/kubelet
    - name: msi
      hostPath:
        path: /var/lib/waagent/ManagedIdentity-Settings
