kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ultrassd
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: UltraSSD_LRS
  kind: managed
  cachingmode: None
  diskIopsReadWrite: "1400"
  diskMbpsReadWrite: "320"
