apiVersion: v1
kind: Pod
metadata:
 name: nginx-azuredisk
spec:
 containers:
  - image: nginx
    name: nginx-azuredisk
    volumeMounts:
      - name: azure
        mountPath: /mnt/disk
 volumes:
      - name: azure
        azureDisk:
          kind: Managed
          diskName: {disk-id}
          diskURI: /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
