---
apiVersion: v1
kind: Pod
metadata:
  name: aspnet-hostpath
spec:
  containers:
  - image: microsoft/aspnet
    name: aspnet-hostpath
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/azure
      subPath: windows
  nodeSelector:
    beta.kubernetes.io/os: windows
  volumes:
  - name: test-volume
    hostPath:
      path: 'C:\'
