apiVersion: apps/v1beta1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: k8stest
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-azurefile
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapache
    spec:
      containers:
      - name: testapache
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: testapache-data
            mountPath: /var/www/html		
      volumes:  
      - name: testapache-data
        persistentVolumeClaim:
          claimName: pvc-azurefile	  
